### ISSUE TITLE
Pad clearing path leaves a little notch of solder mask

### ISSUE THREAD

**Issue by shaun-leach** [MakeraInc/MakeraCAM#10] opened 2024-04-27 19:12 UTC
![image](https://github.com/MakeraInc/MakeraCAM/assets/5731563/7475b42e-c651-4655-9130-dbd82e3f4d14)
![image](https://github.com/MakeraInc/MakeraCAM/assets/5731563/8f4d1fc4-290e-4e42-993a-ba6381bec861)

Not a huge deal but it would be nice if the clearing path didn't do that

**Comment by shaun-leach** [comment] 2024-04-27 19:15
![image](https://github.com/MakeraInc/MakeraCAM/assets/5731563/af1e384f-be30-430b-b252-6d2cd4b48d7a)

Interestingly the CAM software shows the paths as being closed.

**Comment by leighost24** [comment] 2024-04-28 05:54
Could you provide the Gerber files and MKC project file? We will track and analyze the cause of the problem.

**Comment by shaun-leach** [comment] 2024-04-28 21:17
[ContinuitySMT-F_Mask.zip](https://github.com/MakeraInc/MakeraCAM/files/15143806/ContinuitySMT-F_Mask.zip)
Here you go!

**Comment by leighost24** [comment] 2024-07-04 15:51
Fixed in V0.1.2.0

**Closed as completed by leighost24** 2024-07-04 15:51 UTC
